### ISSUE TITLE
Missing tanks

### ISSUE THREAD

**Issue by ats1080** [Phalynx/WoT-Dossier-Cache-to-JSON#22]
Missing tanks:
Pudel
WZ-111 5A
Primo Victoria (for my purposes just used STRV 81 which is in here)
Pz.Kpfw. VII
Tiger 131

Here is what I used to fill them in.  I wasn't sure what the tankid or compDescr was so I just used the values from whatever tank I copied.  Also not sure what the country ID is for the Pudel so I used 8.  I'm assuming it should be 9.

{"tankid": 204, "countryid": 8, "compDescr": 52353, "active": 1, "type": 2, "type_name": "MT", "tier": 6, "premium": 1, "title": "Pudel", "title_short": "Pudel", "icon": "Pl03_PzV_Poland", "icon_orig": "Pl03_PzV_Poland"}
{"tankid": 8, "countryid": 3, "compDescr": 2097, "active": 1, "type": 3, "type_name": "HT", "tier": 10, "premium": 0, "title": "WZ-111 5A", "title_short": "WZ-111 5A", "icon": "Ch41_WZ_111_5A", "icon_orig": "Ch41_WZ_111_5A"}
{"tankid": 37, "countryid": 1, "compDescr": 9489, "active": 1, "type": 3, "type_name": "HT", "tier": 10, "premium": 0, "title": "Pz.Kpfw. VII", "title_short": "Pz.Kpfw. VII", "icon": "G134_PzKpfw_VII", "icon_orig": "G134_PzKpfw_VII"}
{"tankid": 2, "countryid": 1, "compDescr": 529, "active": 1, "type": 3, "type_name": "HT", "tier": 6, "premium": 0, "title": "Tiger 131", "title_short": "Tiger 131", "icon": "G136_Tiger_131", "icon_orig": "G136_Tiger_131"}

Should be all the ones missing for up to 9.19

**Comment by xanthome** [comment]
to the best of my understanding of this http://wiki.vbaddict.net/pages/TypeCompDescr
and https://developers.wargaming.net/reference/all/wot/encyclopedia/vehicles

for instance 
Ch34_WZ131G_FT (tier 6 chinese td)

according to the wargaming apis has "tank_id": 7473,

put 7473 into formula below and you get 3
countryID = typeCompDescr >> 4 & 15

put 7473 into formula below and you get 29
tankID = typeCompDescr >> 8 & 65535

**Comment by Blcz** [comment]
Fixed some time ago. Issue can be closed.
