### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by xanthome** [Phalynx/WoT-Dossier-Cache-to-JSON#23]
{"tankid": 254, "countryid": 1, "compDescr": 65041, "active": 0, "type": 5, "type_name": "SPG", "tier": 1, "premium": 1, "title": "Env_Artillery", "icon": "env_artillery", "icon_orig": "Env_Artillery"},

is on line 5 and 163.

**Comment by Blcz** [comment]
Fixed some time ago. Issue can be closed.
